In [1]:
import numpy as np

In [2]:
time_series = np.array([0, 3, 2, 2, 4, 0, 0, 4, 4, 0, 0])

In [12]:
len(time_series)

11

In [3]:
non_padding = np.where(time_series != 0, 1, 0)
non_padding

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0])

In [13]:
len(non_padding)

11

In [4]:
len(non_padding)

11

In [5]:
prepend = 1 if time_series[0]==0 else 0
append = 1 if time_series[-1]==0 else 0
changes = np.diff(non_padding, prepend=prepend, append=append)
changes

array([-1,  1,  0,  0,  0, -1,  0,  1,  0, -1,  0,  1])

In [14]:
len(changes)

12

In [6]:
start_indices = np.where(changes == -1)[0]
start_indices

array([0, 5, 9])

In [7]:
end_indices = np.where(changes == 1)[0]
end_indices

array([ 1,  7, 11])

In [10]:
for s, e in zip(start_indices, end_indices):
    if e - s < 2:
        non_padding[s:e] = 1

In [11]:
non_padding

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0])